title_name = "Burnout Paradise"
title_id = "45410806"
hash = "0CC027FC408913C2"
media_id = "00000000"

[[patch]]
    name = "Burnout Paradise Breaker Island Disable Render Thread Monitor and FPS counter"
    author = "Adriwin"
    is_enabled = true

    # return BrnRendererModule::RenderThreeThreadMonitors
    [[patch.be32]]  
        address = 0x82405A30
        value = 0x4E800020

    # prevent CgsDev::DebugManager::RenderFrameRateColouredWithAverage call in BrnGame::BrnGameModule::DebugManagerRender
    [[patch.be32]]
        address = 0x823BCEEC
        value = 0x60000000