title_name = "Burnout Paradise"
title_id = "45410806"
hash = "0CC027FC408913C2"
media_id = "00000000"

[[patch]]
    name = "Burnout Paradise Breaker Island Disable FPS Counter"
    author = "Adriwin"
    is_enabled = true

    # Hide FPS counter
    [[patch.string]]
        address = 0x820DDC88
        value = "      "
    
    # Hide Simulation not real time message
    [[patch.string]]
        address = 0x820DDCD4
        value = "                                 "