title_name = "Burnout Paradise"
title_id = "45410806"
hash = "0CC027FC408913C2"
media_id = "00000000"

[[patch]]
    name = "Burnout Paradise Breaker Island Graphics Boost Vehicles LODs Potato"
    description = "This patch changes the LOD distances for vehicles to lower values for maximum performances. It will look horrible so only use this if you have real trouble getting constant 60 FPS."
    author = "Adriwin"
    is_enabled = true

    # Vehicle LOD0 Override Distances (changed to 1 from 10 default)
	[[patch.be32]]
        address = 0x82F307B4
        value = 0x3f800000

    # Vehicle LOD1 Override Distances (changed to 2 from 22 default)
	[[patch.be32]]
        address = 0x82F307B8
        value = 0x40000000

    # Vehicle LOD2 Override Distances (changed to 4 from 35 default)
	[[patch.be32]]
        address = 0x82F307BC
        value = 0x40800000

    # Vehicle LOD3 Override Distances (changed to 6 from 50 default)
	[[patch.be32]]
        address = 0x82F307C0
        value = 0x40c00000

    # Vehicle LOD4 Override Distances (changed to 10 from 70 default)
	[[patch.be32]]
        address = 0x82F307C4
        value = 0x41200000

    # Vehicle Quality LOD Debug Menu Max Value (changed to 1000 from 300 default)
	[[patch.be32]]
        address = 0x8201A258
        value = 0x447a0000